### PR TITLE
docs: update dependabot workflow to add pre-commit message and label

### LINKED ISSUE #503: [FEATURE] Update Dependabot Workflow
### Detailed description

> Current One:

```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
```

Firstly, it should have a proper commit prefix according to conventions, such as `chore(deps)`. Additionally, it lacks a label, which could be helpful for someone looking at the PR, like `📦 dependencies`.

Like this: (looks clean and according to conventions)
image

### Context

I will add the changes with detailed instructions.

> I will do this contribution under GSSoC'23. So, please assign me and I will make a PR.

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Related Issue

Closes: #503 

### Describe the changes you've made

- add appropriate label

```yml
labels:
      - 📦 dependencies
```

- add commit message

```yml
commit-message:
  prefix: 'chore(deps)'
```

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by money8203 — APPROVED** [review]
LGTM 👍

**Review by Deepu178 — CHANGES_REQUESTED** [review]
@Anmol-Baranwal 
vibey-–-Deployment-Overview
same issue. please checkout from issue I think you have not updated the code on your side. looking forward for the updated changes.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal vibey-–-Deployment-Overview same issue. please checkout from issue I think you have not updated the code on your side. looking forward for the updated changes.

I don't understand, I have updated the branch. Why there is a deployment error?

**Review by Deepu178 — APPROVED** [review]
good work @Anmol-Baranwal

**Pull request merged**
