### PR TITLE
fix: add event date and time to card

### LINKED ISSUE #17: [FEATURE] Add event date and time to card
### Detailed description

Add the event date and time above the themes.
image

### Context

You can use `startTime` to add date.

The event component is located at `/src/components/Event`

### Possible implementation

Element you can add
```html
  <div className="mt-2 flex items-center justify-between">
            {new Date(startTime).toUTCString()}
    </div>
```
After:
image

Update the type defination of Event 
```ts

export interface EventInterface {
  id: number;
  title: string;
  description: string;
  startTime: string;
  link: string;
  socials: Array<{ name: SocialIconsNameType; link: string }>;
  themes: string[];
}
```

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 0papi**
## Related Issue

- Information about the related issue

Closes: #17 

### Describe the changes you've made

Add date & time to event card and update typedefs for event to include it.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| 
image
 | 
image|

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Chandraprakash-Darji — COMMENTED** [review]
Kindly share the screenshot of the preview

**Comment by 0papi** [comment]
Please I am unable to get the events from supabase due to environment varables error, how do I obtain them and run the app?

**Comment by Chandraprakash-Darji** [comment]
You can use dummy events that are in `/src/lib/data/event`

**Comment by 0papi** [comment]
please I have included the screenshots

**Comment by Chandraprakash-Darji** [comment]
Thanks for the contributions: @0papi 🚀🚀

**Pull request merged**
