### PR TITLE
Add _document.tsx file in pages directory

### LINKED ISSUE #25: [FEATURE] Add the _document.tsx
### Detailed description

There is no document.tsx file that will have an Open graph, Twitter card, and fonts import and title tag.

### Context

`document.tsx` file should have 
- Open Graph meta tag
-  Twitter card meta tags
-  meta tag for description and author
- favicon for dark and light mode
- Specify lang for page 

## This data can be used
Taken from [Ax Studios](https://github.com/ax-studios/)

You can void repetition by saving the description and title in a variable or you can create component then we can chage for every Page by reusing it.

```tsx
import Document, { Head, Html, Main, NextScript } from 'next/document';
import { ReactElement } from 'react';

class MyDocument extends Document {
  render(): ReactElement {
    return (
      <Html lang="en">
        <Head>
          <link
            rel="icon"
            href="/meta/favicon-dark.svg"
            media="(prefers-color-scheme: dark)"
          />
          <link
            rel="icon"
            href="/meta/favicon-light.svg"
            media="(prefers-color-scheme: light)"
          />

          <meta
            name="description"
            content="Ax Studios is a website designing and development company, which will helps clients achieve their business objectives and promote themselves in the digital."
          />

          <meta name="author" content="Ax Studios" />

          <meta name="robots" content="index, follow" />

          {/* Open Graph */}
          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://axstudios.tech" />
          <meta property="og:image" content="/meta/preview.png" />
          <meta
            property="og:title"
            content="Ax Studio is Digital Software Development/Designing near you"
          />
          <meta
            property="og:description"
            content="Ax Studios is a website designing and development company, which will helps clients achieve their business objectives and promote themselves in the digital."
          />
          <meta property="og:image" content="/meta/preview.png" />

          {/* Twitter  */}
          <meta property="twitter:card" content="summary_large_image" />
          <meta property="twitter:url" content="https://axstudios.tech" />
          <meta
            property="twitter:title"
            content="Ax Studio is Digital Software Development/Designing near you"
          />
          <meta
            property="twitter:description"
            content="Ax Studios is a website designing and development company, which will helps clients achieve their business objectives and promote themselves in the digital."
          />
          <meta property="twitter:image" content="/HomePreview.png" />

          <meta name="theme-color" content="#eb6a50" />
          <link rel="apple-touch-icon" href="/meta/favicon-dark.svg" />

          {/* Fonts */}
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link
            href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,500;0,700;1,900&display=swap"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;

```

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hariscs**
## Related Issue

- Information about the related issue

Closes: #25  

### Describe the changes you've made
added a new file named _document.tsx in the pages directory for adding meta tags , font imports, and title tag.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Documentation update.
- [ ] This change requires a documentation update
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by hariscs** [comment]
hey @Chandraprakash-Darji @mkubdev i only added meta descriptions and OG titles. the favicons are not available in the files that's why I didn't add them.

**Review by Chandraprakash-Darji — CHANGES_REQUESTED** [review]
Very things seem good to me. Just Add the OG and Twitter images. You can use banner that in readme as Image

**Comment by hariscs** [comment]
@Chandraprakash-Darji made requested changes

**Comment by Chandraprakash-Darji** [comment]
Thanks for the contribution

**Review by mkubdev — COMMENTED** [review]
LGTM

**Pull request merged**
