### PR TITLE
SEO improved

### LINKED ISSUE #394: Improve SEO for Project Website
Description:
The current website for the project lacks proper search engine optimization (SEO) techniques, which adversely affects its visibility and discoverability in search engine rankings. This issue aims to address the SEO shortcomings and enhance the website's organic search performance.

Objective:
The objective of this issue is to implement various SEO strategies and best practices to improve the project website's visibility and search engine rankings. By optimizing the website's structure, content, and technical aspects, we can enhance its organic traffic and attract a wider audience.

Tasks:

Conduct a comprehensive SEO audit of the project website to identify existing issues and areas for improvement.
Research relevant keywords and incorporate them strategically into the website's content, including titles, headings, meta descriptions, and image alt tags.
Optimize the website's structure and navigation to enhance user experience and facilitate search engine crawling and indexing.
Implement proper URL structures, including canonical tags and redirects where necessary, to eliminate duplicate content and improve site authority.
Ensure the website's metadata (title tags, meta descriptions) accurately reflect the content and keywords.
Improve the website's page loading speed by optimizing images, minimizing CSS and JavaScript files, and utilizing caching techniques.
Implement schema markup and structured data to enhance search engine understanding of the website's content and improve rich snippets in search results.
Implement XML sitemaps to assist search engine crawlers in discovering and indexing website pages effectively.
Integrate social media sharing buttons to encourage users to share project-related content, thus increasing the website's visibility and potential backlinks.
Monitor website analytics and search engine rankings to assess the impact of SEO improvements and make necessary adjustments.
Expected Outcome:
By addressing the SEO issues and implementing best practices, we expect to see an improvement in the project website's organic search visibility, resulting in increased organic traffic and a broader reach for the project. This, in turn, will enhance the project's exposure, attract more users, and contribute to its overall success.

### PR DESCRIPTION
**Pull request by Avinash905**
## Related Issue

- Information about the related issue

Closes: #394 

### Describe the changes you've made

1. Added some meta tags like title, keywords, language, etc.
2. Corrected some mistakes in already present meta tags of the open graph.
3. Replaced the meta tag image link with the working one.
4. Added lazy loading attribute to all the image tags present in the project.
5. Added aria attributes to the login and register form elements to increase accessibility.
6. Added sitemap.xml file.
7. Placed the heading tags in the correct order.
8. Made the links in the footer accessible.
9. Changed the color of the button text to black because of contrast issues given by the lighthouse.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested using lighthouse score after making the changes.
Overall the site achieved a lighthouse score of 100% in Accessibility, Best Practices, SEO

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Deepu178** [comment]
@Abhinavcode13 Are you experienced in SEO? If yes then connect with me on discord:   deepu178

**Comment by Avinash905** [comment]
> @Abhinavcode13 Are you experienced in SEO? If yes then connect with me on discord: deepu178

Sent you request

**Review by Deepu178 — APPROVED** [review]

**Comment by Deepu178** [comment]
Thanks @Avinash905  for your contribution to your project and looking forward to see more contribution from your side.

**Comment by Avinash905** [comment]
@Deepu178 Could you please add labels to this pr?

**Pull request merged**
