### PR TITLE
Join button issue resolved

### PR DESCRIPTION
**Pull request by HimanshuNarware**
Closes: # 
#187

### Describe the changes you've made
Improve the UI of the Join button
Added hover effect on  Join button

## Type of change
Styling
Hover effect
UI

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?
Tested on laptop and mobile phone.

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
|  

|  | updated screenshot |
| :

 |

##Vide

https://github.com/UniKonf/vibey/assets/83147410/8112d983-6b39-4b24-af86-70d132117a66

o

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Deepu178** [comment]
@HimanshuNarware Thanks for creating the pr but I would suggest you before start working on the issue please get assigned that particular issue.

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware Thanks for creating the pr but I would suggest you before start working on the issue please get assigned that particular issue.

@Deepu178  yep but @J-Harsh said that you can work on this issue

**Comment by Deepu178** [comment]
yeah, but he has not assigned the issue.
Please take care of that these are good practices to follow. 
Are you contributing under GSSoC?

**Comment by HimanshuNarware** [comment]
> yeah, but he has not assigned the issue. Please take care of that these are good practices to follow. Are you contributing under GSSoC?

ok, yes

**Comment by money8203** [comment]
I think this issue has been solved while revamping the new design for the website, thanks for your efforts though Himanshu. You can work on other issues if you'd like :)

**Pull request closed without merging**
