### PR TITLE
feat:update readme banner

### LINKED ISSUE #118: Update the README banner
### Description of the bug

Update the text in the banner "Find your next developer conference and workshop"

### Please add screenshots (if applicable)

image

### Add any other context about the problem here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Ghat0tkach**
## Related Issue

- Information about the related issue

Closes: #118  

### Describe the changes you've made
added readme banner , which changes according to light and dark modes
1 ) Light mode

2)Dark mode

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update.
- [x] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
|image|imaget|
image|image|

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Deepu178** [comment]
@Ghat0tkach Previous one banner looks good for me. Can you please point out something that we should update our banner from previous one to the one that  you have suggested.

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach Previous one banner looks good for me. Can you please point out something that we should update our banner from previous one to the one that  you have suggested.
@Deepu178 @money8203 
Actually in the issue it was mentioned to change the mentioned tagline.I didn't had access to that banner figma file and as suggested created a custom banner with the desired tagline😅

**Comment by Deepu178** [comment]
@Ghat0tkach can you create a custom Figma file for the banner as per your choice.

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach can you create a custom Figma file for the banner as per your choice.
 
The banner I added is already created by me through figma😅

**Comment by Deepu178** [comment]
@Ghat0tkach Thanks for making the contribution to the Vibey and hope you make more contribution to the project Vibey.

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach Thanks for making the contribution to the Vibey and hope you make more contribution to the project Vibey.

Thank you and no doubt will keep on contributing! I'm a beginner in frontend probably will contribute while learning!🚀

**Pull request merged**
