### PR TITLE
Newsletter Functionality and Custom Email Template

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Related Issue

#560

### Describe the changes you've made

This pull request adds the newsletter functionality to the Vibey platform, allowing users to subscribe to our exciting events and updates. Additionally, a custom email template has been created to deliver a personalized experience to each email subscriber.

### Changes Made:

1. Implemented the newsletter subscription feature, allowing users to submit their email addresses.
2. Created a custom email template using Vibey's branding to provide a consistent and attractive look to the emails sent to subscribers.
3. Integrated the email template with the backend to send welcome emails to new subscribers.
4. Updated the email credentials in the nodemailer configuration file to use the email and password of the platform administrator.
### Instructions for Reviewer:

Please test the newsletter subscription feature by entering a valid email address and confirming that the welcome email is received with the custom email template. Make sure to replace the email and password credentials in the nodemailer configuration file (.env) with your own credentials to enable sending emails during testing.

SMPT_MAIL: [your-email@example.com]
SMPT_PASSWORD: [your-email-password]

Please review the changes and ensure that the email subscription and custom email template are functioning correctly. If you have any suggestions or feedback, kindly let me know, and I will be happy to make the necessary adjustments.

Thank you for your review!

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### Video

https://github.com/UniKonf/vibey/assets/85815172/a01fbb09-f16f-49a3-b73f-dab6be0ab538

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@Deepu178 ,please review and merge my pull request ,i have made amazing newsletter with vibey email template also .

**Comment by Deepu178** [comment]
@Nishitbaria why is it taking so much time to subscribe I mean it should be smooth.

**Comment by Nishitbaria** [comment]
> @Nishitbaria why is it taking so much time to subscribe I mean it should be smooth.

@Deepu178 ,It is smtp  mail request and in video ,it is taking  so much time  due to slow internet

**Comment by Nishitbaria** [comment]
> > @Nishitbaria why is it taking so much time to subscribe I mean it should be smooth.
> 
> @Deepu178 ,It is smtp mail request and in video ,it is taking so much time due to slow internet (Also it is free)  ,make sure to  update .env   with your credentials and merge my pull request

**Comment by Deepu178** [comment]
@Nishitbaria can you share the scree recording when your connection is not slow and it works fine.

**Comment by Nishitbaria** [comment]
> @Nishitbaria can you share the scree recording when your connection is not slow and it works fine.

@Deepu178  I have added loading animation,please review and merge my pull request

[screen-capture.webm](https://github.com/UniKonf/vibey/assets/85815172/4ba83ffc-30e0-441b-8705-5490ad261632)

**Comment by Nishitbaria** [comment]
@Deepu178 please review and merge my pull request

**Comment by Nishitbaria** [comment]
@Deepu178 please review and merge my pull request

**Comment by Deepu178** [comment]
@Nishitbaria is it a  paid service?

**Comment by Nishitbaria** [comment]
> @Nishitbaria is it a paid service?

@Deepu178 ,I am using gmail for smtp and nodemailer ,you have just use any gmail credentials

**Comment by Nishitbaria** [comment]
@Deepu178 ,now please review and merge my pull request asap otherwise conflict will occur i request you

**Comment by Nishitbaria** [comment]
@Deepu178 ,now please review and merge my pull request asap otherwise conflict will occur i request you

**Review by Deepu178 — APPROVED** [review]
Thanks @Nishitbaria for your contribution and looking forward for more contribution from your side.

**Pull request merged**
