### PR TITLE
fix: solve the light theme loading problem

### LINKED ISSUE #143: [BUG] Light mode is not loading properly
### Description of the bug

If you set the mode to light and refresh the page for some fraction of a second dark mode is loaded then convert it to light mode.
But no error for the dark mode.

I would like to work on it for gssoc23.

### Please add screenshots (if applicable)

_No response_

### Add any other context about the problem here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by suzy-g38**
## Related Issue

Closes: #143

### Describe the changes you've made

Previously when you set the theme to light mode and refresh the page the dark theme would load first then the light one. I made the necessary changes and now the light theme is loading properly.

## Type of change

What sort of change have you made:

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

Original Video:

https://github.com/UniKonf/vibey/assets/62666287/6c93498f-bbb0-4ea3-b030-eb71dd325960

Updated Video:

https://github.com/UniKonf/vibey/assets/62666287/f02ac2d5-330b-4035-86b0-fbca50f3a192

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Deepu178** [comment]
Please checkout the chekclist and add the screenshot

**Comment by suzy-g38** [comment]
> Please checkout the chekclist and add the screenshot

I will do the checklist part and I will add a video cause screenshot cannot capture the loading scenario.

**Review by suzy-g38 — COMMENTED** [review]
add the necessary comments to the changes

**Comment by suzy-g38** [comment]
> Please checkout the chekclist and add the screenshot

@Deepu178 I have made all the necessary changes that you asked for and also uploaded video as a proof of my work.

**Review by Deepu178 — APPROVED** [review]

**Comment by suzy-g38** [comment]
Hey, @Deepu178 can you label my pr as gssoc23?

**Comment by Deepu178** [comment]
@suzy-g38  labelled it. 
Thank you for making the contribution to the Vibey and hope you will make more contribution to the project.

**Pull request merged**
