### PR TITLE
heading added

### LINKED ISSUE #464: Adding animation on of home page.
### Context

Wish to work under GSSoC'23.

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ShreyaDhiman24**
## Related Issue
Closes: #464 

### Changes

[Screencast from 21-07-23 09:21:42 PM IST.webm](https://github.com/UniKonf/vibey/assets/98320971/4580ccc1-3936-4e48-9ee2-241f4f216243)

- [x] Code style update (formatting, local variables)

## Checklist

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] All of above

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Deepu178** [comment]
@ShreyaDhiman24 this color combo doesn't look good.

**Comment by ShreyaDhiman24** [comment]
> @ShreyaDhiman24 this color combo doesn't look good.

@Deepu178 But this is the colour which website has..do you want me to change it ..?

**Comment by ShreyaDhiman24** [comment]
> > @ShreyaDhiman24 this color combo doesn't look good.
> 
> @Deepu178 But this is the colour which website has..do you want me to change it ..?

What colour would you prefer then for your website..?

**Comment by Deepu178** [comment]
@ShreyaDhiman24 you should try cyan type of colors which will look better.

**Comment by ShreyaDhiman24** [comment]
@Deepu178 I have changed colour. Check out.

**Comment by ShreyaDhiman24** [comment]
[Screencast from 03-08-23 06:37:06 PM IST.webm](https://github.com/UniKonf/vibey/assets/98320971/94a4f45d-1a03-4bae-8760-6b31774c7789)

**Review by Deepu178 — APPROVED** [review]
Thanks @ShreyaDhiman24 for your contribution and looking forward to see more contribution

**Pull request merged**
