### PR TITLE
docs: workflow to add labels on analyzing title/comment based on conditions

### LINKED ISSUE #501: [FEATURE] Workflow to add labels to PR & issues by analyzing titles
### Detailed description

Suppose there is `fix` or `feat` or `chore` or `Feature` in the title, the workflow would automatically add the corresponding labels.

> I would do this under GSSoC'23.

### Context

I will separate this workflow into two files to improve code readability and labels will be in the trigger file.

By analyzing the titles of PRs, it will automatically assign appropriate labels based on predefined criteria such as status, goals, and aspects. It will use `regexs`, `events`, `targets`.

### Possible implementation

I will add detailed instructions in the PR description, so that you can easily review the PR.

I will add the labels, based on the repository and will mention if a new label is used for the purpose like `build`.

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
- Reference: https://github.com/hoho4190/issue-pr-labeler

## Related Issue

Closes #501 

## About Regex Expression

You can test it here: https://regex101.com/

I am taking two examples, which you must read so that you can properly review the PR.

- `/\bfeat\b/`: This regular expression matches the exact word "feat" with word boundaries (`\b`). It will match strings that contain the word "feat" as a whole word, but not if it's part of another word (e.g., "defeat" or "feature").

- `/feature/i`: This regular expression matches the word "feature" (case-insensitive) anywhere within a string. It will match strings that contain "feature" in any combination of uppercase and lowercase letters (e.g., "Feature", "FEATURE", "feature").

### Describe the changes you've made

- I have checked issue forms and corresponding labels to properly use the config workflow.
- I have not made this workflow for analyzing issues, so let me know.
- I didn't found anything related to adding multiple labels at once, so I have used 1 label for 1 set.
- add labels in the repository used in the config file or suggest any changes.

Let me know if you need anything.
Good luck :)

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Deepu178 — APPROVED** [review]
@Anmol-Baranwal there is error. can you check it?

**Review by Deepu178 — CHANGES_REQUESTED** [review]
you should check the errors.

**Comment by Anmol-Baranwal** [comment]
> you should check the errors.

Let me double check it. I will let you know.

**Comment by Anmol-Baranwal** [comment]
I believe this would work. Earlier, I was trying to take issues into account, but I hadn't given read permission for the same. Due to this, an error was arising in the CI activity.

**Comment by Deepu178** [comment]
vibey-–-Deployment-Overview
@Anmol-Baranwal there was no issue with your code. you can checkout in above screen by building it locally.

**Comment by Anmol-Baranwal** [comment]
> vibey-–-Deployment-Overview @Anmol-Baranwal there was no issue with your code. you can checkout in above screen by building it locally.

Yeah, it is running as usual.
image

**Review by Deepu178 — APPROVED** [review]
Thanks for your contribution @Anmol-Baranwal  and looking for more contribution in gh actions.

**Pull request merged**
