### PR TITLE
Fixed Navbar closing for mobile

### LINKED ISSUE #368: [BUG] Navbar remains open on mobile
### I'm in GSSoC'23

On mobile screens, navbar remains open after 
- clicking on any Navbar links

### Expected Behaviour
- Navbar should close instantly and the requested page should be displayed when the user clicks on any Navbar links.

### Please add screenshots (if applicable)

https://github.com/UniKonf/vibey/assets/66116440/0acd2542-cb0b-4f5a-bc91-5e8fe8656625

### Add any other context about the problem here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by anamika7153**
## Related Issue

- Navbar remains open on mobile after clicking any Navlink, logo or outside the Navbar.

Closes: #368 

### Describe the changes you've made

- I have added the functionality of Navbar closing when the user clicks on any link of the Navbar.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Deepu178 — APPROVED** [review]
See the changes in video I have requested.

**Review by Deepu178 — CHANGES_REQUESTED** [review]
https://www.loom.com/share/d3135d40195b446780ba89f7d9ec1c2d?sid=440e3cf8-ecd0-4b3f-90cf-c9b792e7b2a2

**Comment by anamika7153** [comment]
> https://www.loom.com/share/d3135d40195b446780ba89f7d9ec1c2d?sid=440e3cf8-ecd0-4b3f-90cf-c9b792e7b2a2

On it.

**Comment by anamika7153** [comment]
@Deepu178  have a look

**Comment by anamika7153** [comment]
@Deepu178 

https://github.com/UniKonf/vibey/assets/66116440/9ff14ded-5f8f-4b69-8e67-5bf17c3cbf11

**Comment by Deepu178** [comment]
Thanks @anamika7153 for making contribution to the Vibey and please look into other issues or tell me if you want to work on any particular issue.

**Comment by anamika7153** [comment]
> 

sure :)

**Pull request merged**
