### PR TITLE
Vishalk91 4 about issue

### LINKED ISSUE #209: Adding a About Us page.
I can add a about us section/ page and an contact us section preferably in the footer with like address, mail and support number

@J-Harsh could you please assign it to me under GSSOC23

### PR DESCRIPTION
**Pull request by Vishalk91-4**
## Related Issue

- Information about the related issue

Closes: #209  

### Describe the changes you've made

I have created an About.tsx file in the Pages section in that I have added hero image and written about the purpose of Vibey, 
Then I've add a know region where I have added three cards according to the devices, their display may change from 3 to 2 to 1, thosse contain some text about event, cfp and hackathon and a know more button through which they can access the direct links to these pages

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

 I've tested all these changes locally through multiple browsers and across all devices from mobile to laptop so as to make sure the code does not break out

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

Screenshot of About Us Section 
Dark Mode Laptop View
Screenshot 2023-06-04 180925
Screenshot 2023-06-04 183726

Light Mode Mobile View
Screenshot 2023-06-04 184003

image

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

@Deepu178 @J-Harsh could you please review this pull request and if possilbe the PR #233 also which I've updated

### CODE REVIEW

**Comment by Deepu178** [comment]
@Vishalk91-4  You need to fix this
Warning: Run autofix to sort these imports!  simple-import-sort/imports

**Comment by Vishalk91-4** [comment]
@Deepu178 , I've made the changes, could you please review them and also #233 which fixes footer

**Comment by Vishalk91-4** [comment]
@Deepu178 just add the footer.tsx file from issue #233 and check this, if it doesn't impress then I can also add the our team section if you want
Please review it

**Comment by Deepu178** [comment]
@Vishalk91-4  please remove the icons from the footer coz it doesn't look good. After committing these changes your PR will be ready to merge!

**Comment by Vishalk91-4** [comment]
@Deepu178 I have made changes, according to what you said in the footer, could you please check and merge it

**Comment by Deepu178** [comment]
@Vishalk91-4 could you please add screenshot.

**Comment by Vishalk91-4** [comment]
@Deepu178 it's already added if you look, in preview

**Comment by Vishalk91-4** [comment]
@Deepu178 , I'm sorry I thought you were talking about the image in footer

PR no. of footer #233 

Here's the screenshot
image

**Comment by Vishalk91-4** [comment]
@Deepu178, could you please review these two PRs, #243  and #233, merge them

**Comment by Deepu178** [comment]
@Vishalk91-4 I would suggest you to designing the overall about page as it doesn't look as expected.

**Comment by Vishalk91-4** [comment]
@Deepu178 Can you tell what are the other content you want in here

**Comment by Vishalk91-4** [comment]
@Deepu178 , i've made the necessary changes, it's most probably done now, could you please review and merge it

**Comment by Deepu178** [comment]
@Vishalk91-4 You are doing amazing in making efforts but sometimes it's not the way a project look for. Please join the discord channel and ping the maintainers for one to one meeting about this issue.

https://discord.gg/PNYrhJ97

**Comment by Vishalk91-4** [comment]
@Deepu178 okay, I've joined the discord and will be getting in touch with them, can you merge this one, where I've aligned the things #233

**Comment by Deepu178** [comment]
@Vishalk91-4 Any update on this pr?

**Comment by Vishalk91-4** [comment]
@Deepu178 Actually my exams are going on and they will end at 22nd, so I have not updated the page, the design is the same as it was, when you preview it

**Review by Deepu178 — APPROVED** [review]
Thanks @Vishalk91-4 for making the contribution to the project and looking forward for more pr from your side.

**Comment by Vishalk91-4** [comment]
@Deepu178 , could you make this a level 2/3  since a new page was added, level 1 is for bugs
And according to GSSoC23 guidelines it should be 3 not 1

**Pull request merged**
