### PR TITLE
feat: error handling

### LINKED ISSUE #440: [FEATURE]: Error handling for Client Side
### Detailed description

Handle errors for user registration, login and all the pages where data is coming from API

### Context

As currently there is no specific error-handling part, I would work on it

### Possible implementation

_No response_

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by suzy-g38**
## Related Issue

- Information about the related issue

Closes: #440

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Deepu178 — APPROVED** [review]
Thanks for your contribution to the project @suzy-g38 looking for more contribution to the project.

**Comment by Deepu178** [comment]
@suzy-g38 readme is not in the commits.

**Comment by suzy-g38** [comment]
> @suzy-g38 readme is not in the commits.

didn't understand...can you elaborate it please

**Comment by Deepu178** [comment]
@suzy-g38  you have deleted the readme when you pushed the changes. Please recheck again

**Comment by suzy-g38** [comment]
> @suzy-g38 you have deleted the readme when you pushed the changes. Please recheck again

@Deepu178 I have fixed the issue

**Comment by Deepu178** [comment]
Thanks for your contribution to the project and looking forward to see more contribution from your side.

**Pull request merged**
