### PR TITLE
Form for adding event,meetup, hackathons and cfps for contibutors

### LINKED ISSUE #115: create form for adding events, meetups, hackathons and CFPs for contibutors
### Detailed description

Adding events to the database

### Context

Form for contributors to add events 

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Isha988**
## Related Issue
Closes #115 

### Describe the changes you've made

1. Created new input and text area components
2. Created Form

### Note
1. Newly created component can be used in different files and will help in maintaining uniformity in project
2. Form is available at `/dashboard/add_event`. Suggest some way to put it beside side navbar of dashboard page

### CODE REVIEW

**Comment by Deepu178** [comment]
@Isha988 I think the form you have created it doesn't match with the schema on the server. Please have a look on server side for understanding the required field type.

**Comment by Isha988** [comment]
> @Isha988 I think the form you have created it doesn't match with the schema on the server. Please have a look on server side for understanding the required field type.

But, schema is different for each one of three.

**Comment by Deepu178** [comment]
@Isha988 so should we create three forms for adding events, hackathons and cfps or there is any way to create single form but different fields as we select from dropdown. What are your views on it?

**Comment by Isha988** [comment]
> @Isha988 so should we create three forms for adding events, hackathons and cfps or there is any way to create single form but different fields as we select from dropdown. What are your views on it?

I think we can make something similar to tabs, when any option is selected from drop down its corresponding form will be opened.

**Comment by Deepu178** [comment]
yeah that's really so you can create tabs for adding events, hackathons and cfps by checking out the schem on server side and just let me know if you need any help in creating the forms. looking forward to see the changes.

**Comment by Deepu178** [comment]
@Isha988 any update?

**Review by Deepu178 — APPROVED** [review]

**Pull request merged**
