### PR TITLE
chore: Update welcome.yml

### PR DESCRIPTION
**Pull request by mkubdev**
### Describe the changes you've made

Replacing EHub Welcome action by SCP.
Using checkout@v1 instead of v3.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Code of Conduct

- [ x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mkubdev** [comment]
The action still crashes till the PR is merged :
image

**Comment by Chandraprakash-Darji** [comment]
@mkubdev should we merge and test, or the create the demo repo and try there?

**Comment by mkubdev** [comment]
Im not on my computer, but there is some tools to test action localy. Will test and remove the WIP mention once it's ok on my side. ✌️

Don't merge it right now

**Comment by mkubdev** [comment]
Hi back.
The `welcome` action is working locally:
image

The prettier one still bugged, but we can merge this PR.

**Comment by mkubdev** [comment]
Hi back,
The `welcome` github workflow is working locally:
image

The `Prettier` job is still bugged but it's maybe caused by a wrong prettier local file. We can merge this PR.

**Review by Deepu178 — APPROVED** [review]

**Pull request merged**
