### PR TITLE
Fixing Dark Mode Color Contrast Issue on Login and Signup Page

### LINKED ISSUE #518: [FEATURE] Dark Mode Color Contrast Issue on Login and Signup Page
### Detailed description

Expected Behavior:
In Dark Mode, the text should be clearly visible and distinguishable from the background, ensuring good color contrast for readability.

Actual Behavior:
When using the application in Dark Mode, the text color on the login and signup pages appears to be the same as the background color. As a result, the text becomes almost invisible, making it challenging for users to see what they are typing. This creates a usability issue as users cannot accurately input their login or signup information.

### Context

It will enhance the User Experience.

### Possible implementation

_No response_

### Additional information

https://github.com/UniKonf/vibey/assets/104740281/819c62fa-fdd9-4173-abab-f0e9acbb9b87

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

- Information about the related issue

Closes: #518 

## Type of change

What sort of change have you made:
- Wrapped all the input in div and added `dark:text-black` for dark mode.
- Changed the focus color to apply also when selected in `auth.tsx` to make the text visibility better.
- removed `darkMode: "class"` to apply `dark:` classes like `dark:text-black`. 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| image | image |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Deepu178** [comment]
@s2sharpit it's failing in production. Can you check by building locally by running "pnpm run build"

**Comment by s2sharpit** [comment]
> @s2sharpit it's failing in production. Can you check by building locally by running "pnpm run build"

Hey @Deepu178, I found that there is a type error in file `./src/pages/dashboard/add_event.tsx`.
The error is arises after merging of this pr #429 . Can I fix it?

Here is the screenshot of it:

image

image

**Comment by s2sharpit** [comment]
Ohh, there is more problems in same file:
image

**Comment by Deepu178** [comment]
@s2sharpit 
@suzy-g38 has fixed the error and will push the changes soon. so yeah no need to work on already solved issue.

**Review by Deepu178 — APPROVED** [review]
Thanks for making the contribution to the project and looking forward to see more contribution from your side. @s2sharpit 
you have also solve type issue

**Comment by s2sharpit** [comment]
Hey @Deepu178,
I'm a GSSoC23 contributor, so would request you to add appropriate labels to this PR.

**Comment by s2sharpit** [comment]
Hey @Deepu178, Please add appropriate labels to this PR.

**Pull request merged**
