### PR TITLE
refactor: add interface and optimized code in contributions section

### LINKED ISSUE #505: [BUG] Refactor missing properties with interface in GetContributor.tsx
### Description of the bug

- There is a missing `width` & `height` property with `Image` from next.js.

- Also, there is no interface involved in the page. What is even the advantage of TypeScript if we don't restrict type.

I will remove the errors, and add a proper Interface with the current rule set.

- Using `Link` rather than `a`. Reference docs: https://nextjs.org/learn/basics/navigate-between-pages/link-component

> I will do this under GSSoC'23.

### Please add screenshots (if applicable)

image

### Add any other context about the problem here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Related Issue

Closes: #505 

### Describe the changes you've made

- add interface

```typescript
interface Contributor {
  login: string;
  avatar_url: string;
  contributions: number;
  html_url: string;
}
```

- replace `<a>` to `<Link>` with several other minor changes

- fix error shown in the issue description

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
I am currently travelling, so I will fix the errors tomorrow. If there is, since the deployment failed.

**Comment by Deepu178** [comment]
@Anmol-Baranwal no issue

**Comment by Anmol-Baranwal** [comment]
@Deepu178 
It is working fine.

> localhost
image

**Review by Deepu178 — APPROVED** [review]
Thanks for your contribution @Anmol-Baranwal 
cheering up for more contribution

**Comment by Anmol-Baranwal** [comment]
> I believe this should be level 2 since I implemented an interface for type checking and optimized the link.

No worries, I am not here to argue, and I will definitely contribute more.

> Thanks for your contribution @Anmol-Baranwal cheering up for more contribution

**Pull request merged**
