### PR TITLE
[#200]Added Event Perspektywy Women in Tech Summit 2023

### PR DESCRIPTION
**Pull request by NehaKariya0309**
## Related Issue

The file had fewer events information.

Closes: # 200

### Describe the changes you've made

1. Added the event details of Perspektywy Women in Tech Summit 2023 in the Events array.
2. Modifed the cities array(added "Warsaw").
3. An image for the event has been added in the images folder.
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)
Screenshot (85)

Event as in website looks like this-
Screenshot (89)

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Deepu178 — CHANGES_REQUESTED** [review]
@NehaKariya0309 we are using Yarn package manager for installing dependencies and not npm package manager for installation.
Please remove package-lock.json file and install the dependencies using yarn.
Commit those changes.

**Comment by NehaKariya0309** [comment]
@Deepu178 , I have removed the package-lock.json file, installed the dependencies using yarn and committed the changes 2 days ago.

**Comment by NehaKariya0309** [comment]
@Deepu178 , kindly look into my PR, as the event I have added will start this week so it would help add to the content of the website.

**Comment by Deepu178** [comment]
This event is over and there were so branch conflicts that were needed to be resolved. Kindly look into other issues @NehaKariya0309

**Pull request closed without merging**
