### PR TITLE
Updated custom-scrollbar design

### LINKED ISSUE #244: [FEATURE] : Custom scrollbar for light theme
#### As of now "Vibey" have a scroll-bar with custom design but it's color components are same for both `Light Theme` and `Dark Theme` , the current scroll bar looks good in dark theme but its not matching and suiting light theme.

So : 
1. I plan to add custom scroll-bar for light theme
2. I plan to add hover effect on scrollbar so whenever a user hovers the scrollbar it will have a color effect to make it more visually appealling.

### Context

https://github.com/UniKonf/vibey/assets/115401171/f4df78ca-fecb-479c-be3c-cf38e290aa5e

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ujjawaltyagii**
## Related Issue

Closes : #244 

### Describe the changes you've made

1. Earlier `scrollbar-track` (scroll-bar background) wasn't defined and was being set to Black color which was making scrollbar track less visible so I added `scrollbar-track property`.
2. Add hover effect on `scrollbar-thumb` so even in light theme user get to see the difference in scrollbar whenever they hovers on `scrollbar-thumb`

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

https://github.com/UniKonf/vibey/assets/115401171/909b9c53-ae63-4cfd-b8de-2c84c0498f24

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

#### I'm gssoc contributor so please add required labels*

### CODE REVIEW

**Comment by ujjawaltyagii** [comment]
@J-Harsh @Deepu178 please review my PR under `gssoc23` and add level + assignee to this PR

**Comment by ujjawaltyagii** [comment]
@Deepu178 please review this PR as well 🙏

**Comment by money8203** [comment]
@ujjawaltyagii have you checked the new design for our website? The feature you're suggesting was for the old design

**Comment by ujjawaltyagii** [comment]
> @ujjawaltyagii have you checked the new design for our website? The feature you're suggesting was for the old design


@money8203  If you look at the date I opened the issue, the date I was assigned with the issue and the date I opened the PR you will see that It was meant for old design to improve the UI/UX of website. Is it my fault that despite resolving issue in perfect time my PR wasn't reviewed despite messaging here on github and on discord group :)

**Comment by money8203** [comment]
Nobody said it was your fault Ujjwal, some changes needs to be implemented to the website and they're being hit into production along the way.

Also, maintainers are performing their task regularly, they had to cope up with lots of notification and it's not an easy task to review all pr's at once, so having patience is must and tagging them regularly is not a good practice.

you can make changes to the current scrollbar if you feel the necessity, this is not a competition which needs to be worry about

**Comment by ujjawaltyagii** [comment]
PR will be updated soon with the scroll-bar related changes for new website design with 
- Hover effect on scroll-bar for  both light theme and dark theme
- Changed scrollbar-track color in order to make it more visible in both themes

**Pull request closed without merging**
