### PR TITLE
New menu bar created

### PR DESCRIPTION
**Pull request by Varghab**
## Changes Made

I created an interactive menu bar with icons and social handles.

### Describe the changes you've made
- Added Icons.
- Made MenuBar according to the theme of the website. 
- Transferred the Get Started button from Navbar to MenuBar (only for mobile and tablet view)
- Added social handle icons.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Original - 
earlier_menubar
earlier_navbar
## Updated - 
navbar_new
navbar_new_dark
navbar_new_light

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Deepu178 — APPROVED** [review]

**Comment by Deepu178** [comment]
@Varghab This pr is reverted due to "Get Started" button doesn't work on larger devices and make the changes to fix the issue,  and link the issue that will be resolved through this pr.

**Comment by Varghab** [comment]
@Deepu178 Shall I fix this issue and create a new PR?

**Comment by Deepu178** [comment]
@Varghab fix the issue and create a new pr with linking the issue that you are resolving through this pr.

**Comment by Varghab** [comment]
@Deepu178 okay, can you please tell me how the get started button is behaving on larger screens?

**Comment by Deepu178** [comment]
@Varghab It doesn't perform any action and opens the modal for auth.

**Pull request merged**
