### PR TITLE
Added show password feature in login page

### PR DESCRIPTION
**Pull request by SubhamB2003**
## Related Issue
Issue solved: #302 

image

image

- Information about the related issue

Closes: # 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by SubhamB2003** [comment]
@Deepu178 Hey, can you please review it

**Review by Deepu178 — CHANGES_REQUESTED** [review]
@SubhamB2003 I would recommend you to install the dependencies using yarn package manager not npm. Looking for the changes

**Comment by SubhamB2003** [comment]
> @SubhamB2003 I would recommend you to install the dependencies using yarn package manager not npm. Looking for the changes

@Deepu178 Hey, can I also add the preloading screen in there and you can increase the level here?

**Comment by Deepu178** [comment]
@SubhamB2003 just remove the yarn.lock file and commit the changes

**Comment by SubhamB2003** [comment]
> @SubhamB2003 just remove the yarn.lock file and commit the changes

Done

**Comment by Deepu178** [comment]
Thanks @SubhamB2003 for making the contribution to the project. let's solve another issue !

**Comment by SubhamB2003** [comment]
> Thanks @SubhamB2003 for making the contribution to the project. let's solve another issue !

Hey, please the labels
Another thing can I add the preloading screen to this project?

**Comment by Deepu178** [comment]
@SubhamB2003  You can create an issue for this if already not created. I'll see it if not assigned to anyone then I'll assign you.

**Comment by SubhamB2003** [comment]
> @SubhamB2003 You can create an issue for this if already not created. I'll see it if not assigned to anyone then I'll assign you.

ok
Hey, please assign this one https://github.com/UniKonf/vibey/issues/313

**Pull request merged**
