### PR TITLE
Enhanced Footer.tsx

### LINKED ISSUE #210: Enhancing the footer section
The footer section can be improved with, the company logo with a tag line on left side and on the right side we can have a latest type section which lists the link of most recent events and hackathons about to happen, the company section and the social section

@J-Harsh could you please assign it to me under GSSOC23

### PR DESCRIPTION
**Pull request by Vishalk91-4**
## Related Issue

- To Enhance The Current Footer Section

Closes: #210 

### Describe the changes you've made

Added icons, created a modified footer.tsx file, links have been added to all of them, hover effect is present, three sections are there namely, latest which consist links to the most upcoming respective event, workshop or hackathon and a company section then socials section

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [  ] New feature (non-breaking change which adds functionality)
- [  ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [  ] My code follows the guidelines of this project.
- [  ] I have performed a self-review of my own code.
- [  ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [  ] My changes generate no new warnings.
- [  ] I have added tests that prove my fix is effective or that my feature works.
- [  ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

| original screenshot |
Screenshot 2023-06-01 143712 
| updated screenshot |
image

## Code of Conduct

- [  ] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

@J-Harsh could you please review the pull request, most probably the issue is resolved

### CODE REVIEW

**Comment by Vishalk91-4** [comment]
@Chandraprakash-Darji could you please review this pull request

**Comment by Vishalk91-4** [comment]
@Deepu178 I have made changes, according to what you said in the footer, could you please check and merge it

**Comment by Deepu178** [comment]
@Vishalk91-4 
Alignment doesn't look good and we are not using insta.
Also we are not a company.
Checkout checklist before creating pr.

**Comment by Vishalk91-4** [comment]
@Deepu178 , ok I'll change the title there and align them properly, is there something else you would like to be in there

**Review by Deepu178 — APPROVED** [review]

**Comment by Deepu178** [comment]
@Vishalk91-4 Thanks for making the contribution to the Vibey and looking forward for more contribution from your side.

**Pull request merged**
