### PR TITLE
feadAdd Vercel Logo

### LINKED ISSUE #31: [FEATURE] Add 'Powered by Vercel' logo on the footer
### Detailed description

Hi, in order to list this repository as Vercel OSS Sponsor program, we need to brand the footer with this logo:
logo

### Context

In order to match the requirements of Vercel's sponsorship program, we need to add this changes:

- A Vercel banner in the footer of each site page.
- A Vercel banner in the source repository's `README.md` file.
- All links back to Vercel should use a UTM tag with the format: `?utm_source=[team-name]&utm_campaign=oss`.

### Possible implementation

_No response_

### Additional information

More Vercel design content to be found [here](https://vercel.com/design#dark-logotype).
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iambilalriaz**
## Related Issue

- Information about the related issue

Closes: #31 

### Describe the changes you've made

- Added Vercel logo in the footer component
- Added Vercel logo in the README

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| Screenshot 2022-12-12 at 11 24 44 AM | Screenshot 2022-12-12 at 11 23 11 AM |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Chandraprakash-Darji** [comment]
Thanks

**Comment by Chandraprakash-Darji** [comment]
Always attach the screenshot

**Comment by iambilalriaz** [comment]
> Always attach the screenshot

sure

**Comment by iambilalriaz** [comment]
Attached the screenshots

**Review by mkubdev — APPROVED** [review]
LGTM, thanks for  your valuable contribution ✨

**Pull request merged**
