### PR TITLE
footer logo ui fixed

### LINKED ISSUE #82: UI Fixes
### Description of the bug

At the bottom of page , the "Powered by Vercel " where is being written. In white mode it is in white colour and in dark mode it is also in white mode, In white mode the font is also in white color, Which not looks good, or by any mistake it is not taken up in  white mode.

### Please add screenshots (if applicable)

vibey

### Add any other context about the problem here

Change the white to black color font in the file ,make the fill in black

vibey1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sohankasturi**
## Related Issue

- fixed the UI issue that footer logo colour will change automatically after switching to different modes

Closes: #82 

## Screenshots (if applicable)

|      Original       |   
before
|      Updated      |
after

### CODE REVIEW

**Review by Deepu178 — CHANGES_REQUESTED** [review]
Remove unnecessary comments

**Comment by sohankasturi** [comment]
> Remove unnecessary comments

Yeah Sure

**Comment by sohankasturi** [comment]
> Remove unnecessary comments

removed comments

**Comment by sohankasturi** [comment]
> Remove unnecessary comments

zremoved Comments

**Comment by sohankasturi** [comment]
> Remove unnecessary comments

Removed comments can you please check and merge my pull request

**Review by Deepu178 — APPROVED** [review]

**Pull request merged**
